### ISSUE TITLE
Rotating Access Keys

### ISSUE THREAD

**Issue by bbernays** [aws/aws-amplify#114]
I am using the API module to sign requests so I can access API gateway with IAM credentials. When the keys get old and expire the API module won't refresh the keys. In order to force a key refresh I have to refresh the page which forces the entire application to re-authenticate as I am using the <Authenticator>  component.

How am I supposed to force a key refresh without requiring a page reload?

**Comment by bbernays** [comment]
@powerful23 thank you for working on this. Is there any timeline for release?

**Comment by mlabieniec** [comment]
HI @bbernays we have a pr in for this that we are hoping to get our this sprint (released next week). We still need to finish testing but if it doesn't go out this next release i think it will definitely be in the next (we are in a rolling weekly release right now).

**Comment by powerful23** [comment]
@bbernays This should have been fixed in the pr #118 , feel free to reopen this issue if you still got that problem.

**Comment by bbernays** [comment]
@powerful23 Thank you!! I have downloaded the new release and now I am waiting for the keys to expire.

Will definitely report back if there are still issues

**Comment by bbernays** [comment]
The issue unfortunately is not fixed. After the tokens have expired I still require a refresh in order to get valid credentials to interact with my API. 

It seems that the ID token from Cognito Identity is expiring and during the API call it is not refreshing the ID token to in order to get new credentials. 

Now I am getting a ```400 Bad Request``` from ``` https://cognito-identity.us-east-1.amazonaws.com/``` with the message: ```{"__type":"NotAuthorizedException","message":"Invalid login token. Token expired: 1516387425 >= 1516383264"}```

Is there someway of extending the age of the id token from Cognito?

**Comment by powerful23** [comment]
@bbernays Thank you for your feedback. I don't know if there is a way to extend the age. We do refresh the expired credentials when calling APIs but seems like it's not working as expected. We will make more tests on that. So could you show us how to reproduce this that would help a lot.

**Comment by bbernays** [comment]
@powerful23 I will create an example this weekend showing the issue and share a working (and broken) example and code

**Comment by powerful23** [comment]
@bbernays Great! Thanks.

**Comment by bbernays** [comment]
I have created a full example on [Hosted on S3](http://0b587891bb6b0136ce30.com.s3-website-us-east-1.amazonaws.com/)

What example does:
- On component load the page makes a request to an API endpoint which uses IAM for authentication
- When you click on the button it also makes the same request

Steps to reproduce:

1. Signup
2. Login
3. Leave webpage idle for 1 hour
4. Click button 

@powerful23 Let me know if you need anything else. Feel free to email me

**Comment by MatteCarra** [comment]
Thanks @bbernays 
Where can I find the code?

**Comment by bbernays** [comment]
@MatteCarra - I am also using the default Authenticator. I am also only using Cognito UserPools. 

You can check the source code for the example above [here](https://github.com/bbernays/Amplify-Credentials-Issue)

**Comment by bbernays** [comment]
@MatteCarra Can you post an example where refresh token is working with Cognito UserPool is working?

**Comment by MatteCarra** [comment]
@bbernays My code is just as simple as yours. The  only difference was that I was logging in with Facebook federated login.

@powerful23 I forgot to mention that refreshing won't make credentials refresh

I think I'm going to open a new issue because this is a whole different issue

**Comment by bbernays** [comment]
@powerful23 Did you get a chance to test it out?

**Comment by powerful23** [comment]
@bbernays Yes, it works for me.

**Comment by bbernays** [comment]
@powerful23- Here is the screenshot of error I am getting on the example I shared above

![screen shot 2018-01-29 at 11 44 55 am](https://user-images.githubusercontent.com/30294676/35525496-4351df12-04ea-11e8-800e-bae81fdf23f4.png)

**Comment by powerful23** [comment]
@bbernays did you use the PR #188 ? And could you turn on the debug mode so we can have more details about that error? Run ```window.LOG_LEVEL = 'DEBUG'``` in the web console. Thanks.
