### ISSUE TITLE
Token expired: Aws Amplify is not refreshing federated login tokens

### ISSUE THREAD

**Issue by MatteCarra** [aws/aws-amplify#180]
I'm using aws amplify with Facebook and Google federated login and I've noticed that aws amplify is not refreshing federated tokens (I've tested with facebook but I think Google has the same issue) and when I try to execute an api call after facebook token expires I am getting a `400 Bad Request` from `https://cognito-identity.us-east-1.amazonaws.com/` with the message: `{"__type":"NotAuthorizedException","message":"Invalid login token. Token is expired."}`

**Comment by powerful23** [comment]
Closing the issue as this should have been fixed in the latest version

**Comment by MatteCarra** [comment]
Ok thank you
I will test it!

**Comment by MatteCarra** [comment]
I still have a problem.
Yesterday I've logged in with Google and everything worked fine.
Today when I opened again the site aws-amplify called https://cognito-identity.eu-west-1.amazonaws.com/ (Target AWSCognitoIdentityService.GetCredentialsForIdentity) and the endpoint correctly returned `{"Credentials":{"AccessKeyId":"hidden","Expiration":1.522664214E9,"SecretKey":"hidden","SessionToken":"hidden"},"IdentityId":"eu-west-1:hidden"}` and I would have expected that the user was still logged in but Auth.currentAuthenticatedUser() returned the exception: `not authenticated`

**Comment by powerful23** [comment]
@MatteCarra in the current version the ```currentAuthenticatedUser``` method will look into the localStorage to find a user. So did you check your localstorage to see if it was cleaned?

**Comment by MatteCarra** [comment]
![image](https://user-images.githubusercontent.com/11074527/38268323-163bdc64-377e-11e8-9a9b-460bcb261e8b.png)

**Comment by powerful23** [comment]
@MatteCarra I see. It's caused by the Google sdk is not loaded when calling refreshing credentials so it would fail to fetch new credentials for you. Then because of that the library will log user out since they do not have valid credentials now so they need to sign in again.

**Comment by powerful23** [comment]
Closing this issue as the fix has been merged

**Comment by imewish** [comment]
Hello, 

I'm still facing the issue. I'm using the latest version of the amplify. 

I use the below URL to get the Cognito tokens for the Google users and sign them into Cognito pool.

https://' + domain + '/authorize?identity_provider=' + provider + '&response_type=' + type + '&client_id=' + clientId + '&redirect_uri=' + callback + '&scope=' + scope

then, 

```
Auth.federatedSignIn(
      // Initiate federated sign-in with Google identity provider
      `cognito-idp.ap-southeast-1.amazonaws.com/${process.env.VUE_APP_AWS_COGNITO_USER_POOL_ID}`, {
        // the JWT token
        token: token, // received upon login
        // the expiration time
        expires_at: userdata.exp
      },
      // a user object
      user
    )
   .then(res => {
      return Auth.currentCredentials()
    })
```
this method to get aws credentials.

But after exact 1 hour i get token expired error.

**Comment by powerful23** [comment]
@imewish if you are using Cognito Hosted UI to sign in, then you don't need to call `Auth.federatedSignIn` to get the credentials. You just need to call `Auth.currentCredentials()` to get the credentials. For more info: https://aws-amplify.github.io/docs/js/authentication#using-amazon-cognito-hosted-ui

**Comment by powerful23** [comment]
@imewish is it related to #2390

**Comment by imewish** [comment]
@powerful23  im not facing this issue. `User pool groups policies not applied`. 
The issue I'm facing is the AWS credentials received using Auth.federatedSignIn() and Auth.currentCredentials() expires after 1 hour. 

![cognito](https://user-images.githubusercontent.com/11400953/50685137-0df9c400-103e-11e9-90e1-90655f47613f.jpg)

**Comment by powerful23** [comment]
@imewish the credentials will not be automatically refreshed because you didn't provide the refresh handler to the Auth module.

As I mentioned, you should **not** use `Auth.federatedSignIn` when login via Cognito Hosted UI, which is to prevent some unexpected behaviors. If you are just using Cognito Hosted UI correctly, the credentials will be automatically refreshed. 

Since you said:

> With Auth.currentCredentials() i can get the credentials. but with that credentials, I couldn't assume IAM roles from Cognito user pool user groups. where I group my users with different IAM role access.

I think this should be related to that issue. Btw, how are you using `Auth.federatedSignIn` to assume those roles?

**Comment by imewish** [comment]
@powerful23 

> I think this should be related to that issue. Btw, how are you using Auth.federatedSignIn to assume those roles?

the same way that you mentioned in #2390. 

1. Assign an value to the Precedence in your user group
2. In your Cognito Federated Identity pool -> Edit Identity Pool -> Authentication Providers -> Authentication role selection -> Change Use default role to Choose role from token

I have few groups in my user pool. admin, and some others. each of them have different IAM roles. 

if i just use Auth.currentCredentials() the credentials that im getting on the response will not have the IAM role rights from the user group. Instead i get the roles from Unauthentiacted role of my identitiy pool.

If i call Auth.federatedSignIn() and then Auth.currentCredentials() i get the correct credentials.

> the credentials will not be automatically refreshed because you didn't provide the refresh handler to the Auth module.

https://aws-amplify.github.io/docs/js/authentication#launching-the-hosted-ui

above is the exact method im following for login my Federated users(only google). 

by redercting users to this,
`const url_to_google = 'https://' + domain + '/oauth2/authorize?redirect_uri=' + redirectSignIn + '&response_type=' + responseType + '&client_id=' + clientId + '&identity_provider=Google';`

And i could see from the docs this,

![screen shot 2019-01-06 at 8 07 09 pm](https://user-images.githubusercontent.com/11400953/50737399-c0708900-11ee-11e9-8606-1622cd0f364a.jpg)

So it is supposed to refresh the credentials automatically right? without any refresh handlers?

**Comment by powerful23** [comment]
@imewish no, the `Refreshing JWT Tokens` is only for the case if you are using third party as the provider of `Cognito Federated Identity Pool`. 

When using Cognito Hosted UI with the third party provider, what happend is that it will create a federated user in your user pool, and the Cognito service will return back the tokens (idToken, accessToken and refreshToken) of that user to you.

Let's confirm this. Can you check your app to see if these tokens are stored in the local Storage when you signed in from the federated providers using Cognito Hosted UI?

**Comment by imewish** [comment]
Yes. I can see it my local storage.
with a key,

aws-amplify-federatedInfo
![screen shot 2019-01-08 at 7 17 22 am](https://user-images.githubusercontent.com/11400953/50804834-bd23ed00-1315-11e9-92f6-430db14ba99e.jpg)
the key `aws-amplify-federatedInfo` has the idToken , expires_at, and provide as `cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_xxxxx`

**Comment by powerful23** [comment]
@imewish this is not the one I am looking for. This item is cached after you called `Auth.federatedSignIn()`. What I am looking for is those keys like this:
![screen shot 2019-01-08 at 10 05 44 am](https://user-images.githubusercontent.com/11042868/50849860-10ee0080-132d-11e9-9720-3a78acd8fe7e.png)

If there are no such keys under your local storage, then it means you are not signed in correctly with Cognito Hosted UI.

**Comment by imewish** [comment]
@powerful23 

I can see the above credentials like above when I sign in using Cognito pool users, who signed up using, `Auth.signUp` methods,

For the federated google(Who added to the user pool on the first time login and Cognito provides the tokens for them as you mentioned above) the user's I cannot see this kind of credentials.

Again, these are the methods i follow for log in federated user's,

```import Amplify from 'aws-amplify';

const oauth = {
    // Domain name
    domain : 'your-domain-prefix.auth.us-east-1.amazoncognito.com', 

    // Authorized scopes
    scope : ['phone', 'email', 'profile', 'openid','aws.cognito.signin.user.admin'], 

    // Callback URL
    redirectSignIn : 'http://www.example.com/signin/', 

    // Sign out URL
    redirectSignOut : 'http://www.example.com/signout/',

    // 'code' for Authorization code grant, 
    // 'token' for Implicit grant
    responseType: 'token',

    // optional, for Cognito hosted ui specified options
    options: {
        // Indicates if the data collection is enabled to support Cognito advanced security features. By default, this flag is set to true.
        AdvancedSecurityDataCollectionFlag : true
    }
}

Amplify.configure({
    Auth: {
        // other configurations...
        // ....
        oauth: oauth
    },
    // ...
});```

```
const config = Auth.configure();
const { 
    domain,  
    redirectSignIn, 
    redirectSignOut,
    responseType } = config.oauth;

const clientId = config.userPoolWebClientId;
// If you only want to log your users in with Google or Facebook, you can construct the url like:
const url_to_google = 'https://' + domain + '/oauth2/authorize?redirect_uri=' + redirectSignIn + '&response_type=' + responseType + '&client_id=' + clientId + '&identity_provider=Google';



// Launch Google/Facebook login page
window.location.assign(url_to_google);

```

amplify-exporst.js 

```const awsExports = {
  Auth: {
    identityPoolId: 'ap-southeast-1:xxxxxxx,
    region: 'ap-southeast-1',
    userPoolId: 'ap-southeast-xxxx',
    userPoolWebClientId: 'xxxx',
    mandatorySignIn: false,
  },
  Analytics: {
    disabled: true
  }
}

export default awsExports

````
attribute mapping for Google in cognito user pool,
![screen shot 2019-01-09 at 6 59 11 am](https://user-images.githubusercontent.com/11400953/50869972-31c15f00-13dc-11e9-8659-22f68980f707.jpg)



Am I missing anything in the config?

**Comment by powerful23** [comment]
@imewish your configuration seems fine to me as Iong as you can login from Google and get redirected back. The thing is missing is that you didn't listen on the `Hub` events `signIn` which will be fired once the credentials are cached in the storage.

There is some sample code that may help you: https://aws-amplify.github.io/docs/js/authentication#make-it-work-in-your-app

The hub related code:
```js
onHubCapsule(capsule) {
    // The Auth module will emit events when user signs in, signs out, etc
    const { channel, payload, source } = capsule;
    if (channel === 'auth') {
      switch (payload.event) {
        case 'signIn':
          console.log('signed in');
          this.setState({authState: 'signedIn'});
          break;
        case 'signIn_failure':
          console.log('not signed in');
          this.setState({authState: 'signIn'});
          break;
        default:
          break;
      }
    }
  }
```

**Comment by imewish** [comment]
@powerful23 

I have made some progress on this, i used a refresh handler with the auth module like this,

```
Auth.configure({
        refreshHandlers: {
            'cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_xxxx': refreshToken // the property could be 'google', 'facebook', 'amazon', 'developer', OpenId domain
        }
    })
```
```
function refreshToken() {
  return new Promise(resolve => {  // made the change here, there was a syntax error
    const data = {
      token: token, // the token from the provider
      expires_at: userdata.exp,
      identity_id: identity_id // the timestamp for the expiration
    }
    resolve(data);
  });
}
```
This refreshed my temoporary AWS credentials. 
![screen shot 2019-01-11 at 5 57 20 am](https://user-images.githubusercontent.com/11400953/51005894-c0fa7e00-1566-11e9-8533-0b3862eeb2ac.jpg)

but after few hours when i refresh the page, i get this.

![screen shot 2019-01-11 at 5 36 37 am](https://user-images.githubusercontent.com/11400953/51005926-e1c2d380-1566-11e9-88b2-2a4187ec23e6.jpg)

This is very confusing. :(

**Comment by imewish** [comment]
@powerful23 how can i refresh this login token with amplify?

**Comment by powerful23** [comment]
@imewish the `refreshHandler` won't help in this case because it's only for refreshing tokens when federating with the Cognito Federated Identity Pool.

Did you use the hub module to listen on the auth events?

**Comment by vanpra1** [comment]
@imewish were you able to progress further on this one? I am pretty much getting same errors as you do. The only difference in my case is that I am using openid. Please share your findings

**Comment by imewish** [comment]
@vanpra1 my issue got solved.

The issue with my settings was, I was configuring `oauth` inside my signIn component. Had configure the same inside project's `main.js` file. 

```
import Vue from 'vue'
import App from './App'
import router from './router'
import Amplify, { Auth, Hub, Logger } from 'aws-amplify'
import awsExports from '../config/aws-exports'

Vue.config.productionTip = false

const oauth = {
  domain : process.env.VUE_APP_AWS_COGNITO_USER_POOL_DOMAIN, 
  scope : ['openid','email', 'profile'], 
  redirectSignIn : process.env.VUE_APP_AWS_COGNITO_CALLBACK_URL, 
  redirectSignOut : process.env.VUE_APP_AWS_COGNITO_SIGNOUT_URL,
  responseType: 'code'
}

Amplify.configure(awsExports)

Amplify.configure({
  Auth: {
    oauth: oauth
  }
})  

// Amplify.Logger.LOG_LEVEL = 'DEBUG'

const logger = new Logger('main')

Auth.currentUserInfo()
  .then(user => logger.debug(user))
  .catch(err => logger.debug(err))

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: {
    App
  }
})
```
Which made the app to send correct `auth` events to cognition. 

then use `onHubCapsule` to capture the `auth` events and to login/logout users.

```
logger.onHubCapsule = (capsule) => {
      console.log(capsule.payload.event)
      if(capsule.payload.event === 'signIn') {
          console.log('user signed in'); 
          Auth.currentAuthenticatedUser().then((data) => {
              AmplifyStore.commit('setUser', jwt(data.signInUserSession.idToken.jwtToken))
              AmplifyStore.dispatch('authenticate', {
              })
          });
      }
    }
```

**Comment by vanpra1** [comment]
@imewish thanks for sharing. Did you include refreshHandlers?

**Comment by imewish** [comment]
@vanpra1 when you use the above method, you don't need a refresh handler. When the user logs in, refresh token is generated and will be stored in your local storage.
