### ISSUE TITLE
[RN] Unauthenticated users on Pinpoint

### ISSUE THREAD

**Issue by wanytprograms** [aws/aws-amplify#383]
I am trying to integrate aws-amplify (0.2.7) with React Native for Pinpoint analytics. So far, I'm running into an issue where if user is unauthenticated and the app is forced closed and reopened, a new Cognito Federated Identity Id is retrieved. On the Pinpoint dashboard, it shows up as multiple users when it should be one unique user and I can see the same result on Cognito Federal Identities.

I'm not sure if this is a bug, but if it's the expected behavior for aws-amplify, is there a way to link the identity ID to the device for an unauthenticated user? Or will this require setting up user pools with authentication?

Is there an alternate way to achieve what I'm describing for Pinpoint analytics?

I'm new to using aws-amplify, so let me know what other info would be helpful. Thank you all for your work on aws-amplify!

**Comment by jonninja** [comment]
I am seeing the same thing on the web site. I mostly just want to use amplify for easy access from the web to an API. But on every page reload, a new unauthenticated user is retrieved. I figured this would be stored in localstorage or cookie or something, but that doesn't seem to be happening for unauthenticated users (there does seem to be code to cache the federated login, but it's not being used for the unauthenticated users). 

I think I'm in the same boat in not really understanding what is supposed to be happening here.

**Comment by tcscott** [comment]
We have a similar need to cache unauthenticated identity ids in our app, would love to be able to use amplify if it could handle this.

**Comment by brianfoody** [comment]
@wanytprograms I can't even figure out how to get anonymous credentials to call my API. I am calling Amplify.configure but it's not giving me anything. Do you have an example?

**Comment by buggy** [comment]
This is partly related to #308 and a bunch of other issues here :(

**Comment by mlabieniec** [comment]
Caching the unauthenticated identities, especially in regards to analytics is in our backlog.

@brianfoody Anonymous credentials are always retrieved immediately if the Identity Pool has unauthenticated access configured. If you are using Mobile Hub / awsmobile-cli + user-signin most of this is configured for you, but if you configure it yourself, you need to be sure you setup your IAM Unauthenticated role within your Cognito Identity Pool to have the [appropriate permissions for pinpoint analytics](https://docs.aws.amazon.com/pinpoint/latest/developerguide/permissions-actions.html), which is essentially:

```js
"Effect": "Allow",
"Action": "mobiletargeting:*",
"Resource": "*"
```

Similarly with an unauthenticated [API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access-using-iam-policies-to-invoke-api.html)

If you just want to call an http endpoint i.e. not use the sigv4 signing to call an AWS API, I would recommend you just use the fetch() api that's available in both web and react native by the platform. 

Question:
What would be the use case to call a random REST API with the API category outside using fetch() ?

I can add this into our backlog, just trying to understand the use case thanks!

**Comment by Jun711** [comment]
Hi @mlabieniec, just wonder if this Caching the unauthenticated identities function is available via another aws library?

**Comment by powerful23** [comment]
This should have been fixed in latest version.

**Comment by brianfoody** [comment]
@mlabieniec unfortunately I am still getting this issue of new identity id's with version 0.3.3 on React Native 0.54.0. Is there a way to save the identity id and pass it in again or something?

**Comment by powerful23** [comment]
@brianfoody you can define your endpoint id or user id yourself. Please check this [link](https://aws.github.io/aws-amplify/media/analytics_guide#manual-setup). Also could you check the identityId you get by using `Auth.currentCredentials()` to see if you do get different ids every time.

**Comment by brianfoody** [comment]
Hey @powerful23 . Ah okay but that's only for pinpoint analytics reporting that you can specify the userId. It's the underlying identity that I'm worried about changing as I'm using multiple AWS services and need the same identity id across them.

I am checking `Auth.currentCredentials() -> credentials.params.IdentityId` and it's different every time I reload the app at the moment.

**Comment by powerful23** [comment]
@brianfoody confirmed this is a bug for React native app. Fixing it.
