### ISSUE TITLE
Issues signing in and out after upgrade (0.2.12)

### ISSUE THREAD

**Issue by JakeSidSmith** [aws/aws-amplify#543]
#### Do you want to request a feature or report a bug?

Bug

#### What is the current behavior?

Sign in and sign out stopped working in `0.2.12`. Unsure exactly which version we had installed prior to the upgrade, but our `package.json` has `^0.2.9` in it.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

After upgrading with `npm upgrade` our existing sign in and out calls began to fail (with 400s).

Sign in gave the error `signin failed` but still logged the user in (upon reloading the `currentAuthenticatedUser` returned a user), sign out then gave the error `Failed to load creadentials`, and did not sign the user out, so they were stuck inside our app.

#### What is the expected behavior?

Calling sign in and sign out should not error.

#### Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

Browser: Chrome 65.0.3325.181 (Official Build) (64-bit)
OS: Mac OS X El Capitan 10.11.6
Node: 6-8

Used to work in `0.2.9` and possibly up to `0.2.11`. Broke at some point between `0.2.9` and `0.2.12`.

**Comment by powerful23** [comment]
@JakeSidSmith this issue seems to be related to #510 which will happen when unauthenticated access is not enabled in the identity pool.

**Comment by JakeSidSmith** [comment]
Signing in with debug enabled.

<img width="759" alt="screen shot 2018-03-29 at 09 44 14" src="https://user-images.githubusercontent.com/5850625/38079050-038089cc-3336-11e8-9679-6c253dff8da0.png">

**Comment by JakeSidSmith** [comment]
Need any more detailed screenshots?

**Comment by powerful23** [comment]
@JakeSidSmith I had this issue too which is caused by caching and did some fix around that yesterday. Could you try the latest version of amplify to see it works? And also could you check that bad http request to cognito?

**Comment by JakeSidSmith** [comment]
Have just tried `0.2.14`.

Signout fails, but returns no errors.
Upon reload `currentAuthenticatedUser` still returns the user.
Signin still gives `signin failed` error.

Here's the signout call:

<img width="909" alt="screen shot 2018-04-03 at 11 25 28" src="https://user-images.githubusercontent.com/5850625/38244300-1cff509a-3732-11e8-97b4-00b580f5351b.png">

**Comment by powerful23** [comment]
@JakeSidSmith Signout fails is correct if you didn't enable unauthenticated users in your identity pool.
Can you check your localStorage when signing out to see if items with prefix ```CognitoIdentitySerivceProvider``` are removed?

**Comment by JakeSidSmith** [comment]
@powerful23 I can't find any documentation about `unauthenticated` users. What does this mean? Can you link me to some info?

**Comment by JakeSidSmith** [comment]
Upon loading my app initially there is a single `CognitoIdentitySerivceProvider`:

<img width="188" alt="screen shot 2018-04-04 at 10 03 13" src="https://user-images.githubusercontent.com/5850625/38298530-8361ed80-37ef-11e8-9b78-3087adec4a26.png">

If I try to sign in, which errors with `signin failed` I get these:

<img width="207" alt="screen shot 2018-04-04 at 10 03 36" src="https://user-images.githubusercontent.com/5850625/38298561-9ce0d3d4-37ef-11e8-8e95-cd16038e894f.png">

And these are not removed on signout, even though the user appears to signout without issues.

Note: upon reload I am logged back in, as `currentAuthenticatedUser` returns a user.

**Comment by powerful23** [comment]
@JakeSidSmith the error message you received when signing out is saying that you cannot get the guest credentials from Cognito identity pool because you didn't allow unauthenticated access to that pool. You can check this setting in the identity pool console.

Can you clean up the localStorage and try again with sign in. If it fails again because of "cannot load cognito credentials", please confirm your auth configuration and check the http request sent to ```cognito-identity.eu-west-1.amazonaws.com``` to see if you are hitting the correct endpoint.

**Comment by mathewpower** [comment]
Hi @powerful23 I'm working on this with @JakeSidSmith . We're a little confused as to what we need to set up. We are not actually using Identity Pools. Instead we have a User Pool which we are using in API Gateway to authorise against. 

From what I can tell, Identity Pools are used to grant federated access to AWS services which isn't what we're doing so granting unauthenticated access also doesn't make too much sense.

**Comment by powerful23** [comment]
@mathewpower we use the jwt token from the user session to create an identity in that identity pool so that the user can get an aws credentials which allows him to use other aws services like S3, Pinpoint. For now we bind these two together(user pool and identity pool) as this is the most common use case but yes, we might need to support the case if developer just want to use the User Pool to get user sign in. We will have a work around this next week.

**Comment by powerful23** [comment]
Closing this issue as it should have been fixed in the latest version.

**Comment by jamesoflol** [comment]
I'm in same boat. I have Amplify somehwat working without cognito identity pool now, but it still throws errors to me about the identity pool not being set.

'amazon-cognito-identity-js' (which seems to be inappropriately named, as it's for user pools?) has been sucked in to this repo as a child component. That sends a pretty strong signal that anyone who wants to use user pools at all is supposed to use Amplify. But I'm constantly finding that I have to fight around all the other features/federation that is being pushed on me. It's the simplest use case.. surely it's one of the most common?

Should we be using Amplify?

**Comment by VijaySidhu** [comment]
POST https://cognito-identity.us-west-2.amazonaws.com/ 400 () when signing out
